//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Client.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertCoadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertStivaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFromStivaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFromCoadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowCoadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowStivaOperationCompleted;
        
        private System.Threading.SendOrPostCallback sortCoadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback sortStivaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Client.Properties.Settings.Default.Client_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event InsertCoadaCompletedEventHandler InsertCoadaCompleted;
        
        /// <remarks/>
        public event InsertStivaCompletedEventHandler InsertStivaCompleted;
        
        /// <remarks/>
        public event DeleteFromStivaCompletedEventHandler DeleteFromStivaCompleted;
        
        /// <remarks/>
        public event DeleteFromCoadaCompletedEventHandler DeleteFromCoadaCompleted;
        
        /// <remarks/>
        public event ShowCoadaCompletedEventHandler ShowCoadaCompleted;
        
        /// <remarks/>
        public event ShowStivaCompletedEventHandler ShowStivaCompleted;
        
        /// <remarks/>
        public event sortCoadaCompletedEventHandler sortCoadaCompleted;
        
        /// <remarks/>
        public event sortStivaCompletedEventHandler sortStivaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertCoada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] InsertCoada(int i) {
            object[] results = this.Invoke("InsertCoada", new object[] {
                        i});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void InsertCoadaAsync(int i) {
            this.InsertCoadaAsync(i, null);
        }
        
        /// <remarks/>
        public void InsertCoadaAsync(int i, object userState) {
            if ((this.InsertCoadaOperationCompleted == null)) {
                this.InsertCoadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertCoadaOperationCompleted);
            }
            this.InvokeAsync("InsertCoada", new object[] {
                        i}, this.InsertCoadaOperationCompleted, userState);
        }
        
        private void OnInsertCoadaOperationCompleted(object arg) {
            if ((this.InsertCoadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertCoadaCompleted(this, new InsertCoadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertStiva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] InsertStiva(int i) {
            object[] results = this.Invoke("InsertStiva", new object[] {
                        i});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void InsertStivaAsync(int i) {
            this.InsertStivaAsync(i, null);
        }
        
        /// <remarks/>
        public void InsertStivaAsync(int i, object userState) {
            if ((this.InsertStivaOperationCompleted == null)) {
                this.InsertStivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertStivaOperationCompleted);
            }
            this.InvokeAsync("InsertStiva", new object[] {
                        i}, this.InsertStivaOperationCompleted, userState);
        }
        
        private void OnInsertStivaOperationCompleted(object arg) {
            if ((this.InsertStivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertStivaCompleted(this, new InsertStivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFromStiva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] DeleteFromStiva() {
            object[] results = this.Invoke("DeleteFromStiva", new object[0]);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFromStivaAsync() {
            this.DeleteFromStivaAsync(null);
        }
        
        /// <remarks/>
        public void DeleteFromStivaAsync(object userState) {
            if ((this.DeleteFromStivaOperationCompleted == null)) {
                this.DeleteFromStivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFromStivaOperationCompleted);
            }
            this.InvokeAsync("DeleteFromStiva", new object[0], this.DeleteFromStivaOperationCompleted, userState);
        }
        
        private void OnDeleteFromStivaOperationCompleted(object arg) {
            if ((this.DeleteFromStivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFromStivaCompleted(this, new DeleteFromStivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFromCoada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] DeleteFromCoada() {
            object[] results = this.Invoke("DeleteFromCoada", new object[0]);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFromCoadaAsync() {
            this.DeleteFromCoadaAsync(null);
        }
        
        /// <remarks/>
        public void DeleteFromCoadaAsync(object userState) {
            if ((this.DeleteFromCoadaOperationCompleted == null)) {
                this.DeleteFromCoadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFromCoadaOperationCompleted);
            }
            this.InvokeAsync("DeleteFromCoada", new object[0], this.DeleteFromCoadaOperationCompleted, userState);
        }
        
        private void OnDeleteFromCoadaOperationCompleted(object arg) {
            if ((this.DeleteFromCoadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFromCoadaCompleted(this, new DeleteFromCoadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowCoada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] ShowCoada() {
            object[] results = this.Invoke("ShowCoada", new object[0]);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void ShowCoadaAsync() {
            this.ShowCoadaAsync(null);
        }
        
        /// <remarks/>
        public void ShowCoadaAsync(object userState) {
            if ((this.ShowCoadaOperationCompleted == null)) {
                this.ShowCoadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowCoadaOperationCompleted);
            }
            this.InvokeAsync("ShowCoada", new object[0], this.ShowCoadaOperationCompleted, userState);
        }
        
        private void OnShowCoadaOperationCompleted(object arg) {
            if ((this.ShowCoadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowCoadaCompleted(this, new ShowCoadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ShowStiva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] ShowStiva() {
            object[] results = this.Invoke("ShowStiva", new object[0]);
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void ShowStivaAsync() {
            this.ShowStivaAsync(null);
        }
        
        /// <remarks/>
        public void ShowStivaAsync(object userState) {
            if ((this.ShowStivaOperationCompleted == null)) {
                this.ShowStivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowStivaOperationCompleted);
            }
            this.InvokeAsync("ShowStiva", new object[0], this.ShowStivaOperationCompleted, userState);
        }
        
        private void OnShowStivaOperationCompleted(object arg) {
            if ((this.ShowStivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowStivaCompleted(this, new ShowStivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sortCoada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] sortCoada(int[] vec) {
            object[] results = this.Invoke("sortCoada", new object[] {
                        vec});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void sortCoadaAsync(int[] vec) {
            this.sortCoadaAsync(vec, null);
        }
        
        /// <remarks/>
        public void sortCoadaAsync(int[] vec, object userState) {
            if ((this.sortCoadaOperationCompleted == null)) {
                this.sortCoadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsortCoadaOperationCompleted);
            }
            this.InvokeAsync("sortCoada", new object[] {
                        vec}, this.sortCoadaOperationCompleted, userState);
        }
        
        private void OnsortCoadaOperationCompleted(object arg) {
            if ((this.sortCoadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sortCoadaCompleted(this, new sortCoadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/sortStiva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] sortStiva(int[] vec) {
            object[] results = this.Invoke("sortStiva", new object[] {
                        vec});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void sortStivaAsync(int[] vec) {
            this.sortStivaAsync(vec, null);
        }
        
        /// <remarks/>
        public void sortStivaAsync(int[] vec, object userState) {
            if ((this.sortStivaOperationCompleted == null)) {
                this.sortStivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsortStivaOperationCompleted);
            }
            this.InvokeAsync("sortStiva", new object[] {
                        vec}, this.sortStivaOperationCompleted, userState);
        }
        
        private void OnsortStivaOperationCompleted(object arg) {
            if ((this.sortStivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sortStivaCompleted(this, new sortStivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertCoadaCompletedEventHandler(object sender, InsertCoadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertCoadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertCoadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void InsertStivaCompletedEventHandler(object sender, InsertStivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertStivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertStivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteFromStivaCompletedEventHandler(object sender, DeleteFromStivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFromStivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFromStivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void DeleteFromCoadaCompletedEventHandler(object sender, DeleteFromCoadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFromCoadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFromCoadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ShowCoadaCompletedEventHandler(object sender, ShowCoadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowCoadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowCoadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ShowStivaCompletedEventHandler(object sender, ShowStivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowStivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowStivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void sortCoadaCompletedEventHandler(object sender, sortCoadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sortCoadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sortCoadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void sortStivaCompletedEventHandler(object sender, sortStivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sortStivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sortStivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591